Repository dnd-side-project/dnd-11th-6-frontend, pull requests merged in 2024-09, with the labels that each got.

#89 Refactor/chip refac
  src/app/meeting-home/page.tsx
  src/components/Chip/index.stories.tsx
  src/components/Chip/index.tsx
Labels: refactor

#88 Feature/refactor input components
  jest.config.ts
  src/__mocks__/next/image.tsx
  src/__mocks__/svgMock.tsx
  src/app/create-meeting/_components/MeetingDate.tsx
  src/app/create-meeting/_components/MeetingInfo.tsx
  src/app/entry-meeting/_components/LinkInput.tsx
  src/app/entry-meeting/_components/NicknameInput.tsx
  src/app/entry-meeting/_components/PasswordInput.tsx
  src/app/manage-mission/_components/NewMission.tsx
  src/components/Input/index.stories.tsx
  src/components/Input/index.tsx
  src/components/Inputs/CheckboxInput/index.stories.tsx
  src/components/Inputs/CheckboxInput/index.tsx
  src/components/Inputs/DateInput/index.stories.tsx
  src/components/Inputs/DateInput/index.tsx
  src/components/Inputs/TextInput/index.stories.tsx
  src/components/Inputs/TextInput/index.tsx
  src/components/Inputs/TextareaInput/index.stories.tsx
  src/components/Inputs/TextareaInput/index.tsx
  src/components/Inputs/__tests__/CheckboxInput.test.tsx
  src/components/Inputs/__tests__/DateInput.test.tsx
  src/components/Inputs/__tests__/TextInput.test.tsx
  src/components/Inputs/__tests__/TextareaInput.test.tsx
  src/components/Inputs/types.ts
Labels: refactor

#91 Staging
  .vscode/settings.json
  jest.config.ts
  package.json
  src/__mocks__/next/image.tsx
  src/__mocks__/svgMock.tsx
  src/app/create-meeting/_components/MeetingDate.tsx
  src/app/create-meeting/_components/MeetingInfo.tsx
  src/app/create-meeting/_components/MeetingLayout.tsx
  src/app/create-mission/page.tsx
  src/app/entry-meeting/_components/LinkInput.tsx
  src/app/entry-meeting/_components/MeetingInfo.tsx
  src/app/entry-meeting/_components/NicknameInput.tsx
  src/app/entry-meeting/_components/PasswordInput.tsx
  src/app/manage-mission/_components/NewMission.tsx
  src/app/meeting-home/page.tsx
  src/components/Button/index.stories.tsx
  src/components/Button/index.test.tsx
  src/components/Button/index.tsx
  src/components/Chip/index.stories.tsx
  src/components/Chip/index.tsx
  src/components/Input/index.stories.tsx
  src/components/Input/index.tsx
  src/components/Inputs/CheckboxInput/index.stories.tsx
  src/components/Inputs/CheckboxInput/index.tsx
  src/components/Inputs/DateInput/index.stories.tsx
  src/components/Inputs/DateInput/index.tsx
  src/components/Inputs/TextInput/index.stories.tsx
  src/components/Inputs/TextInput/index.tsx
  src/components/Inputs/TextareaInput/index.stories.tsx
  src/components/Inputs/TextareaInput/index.tsx
  src/components/Inputs/__tests__/CheckboxInput.test.tsx
  src/components/Inputs/__tests__/DateInput.test.tsx
  src/components/Inputs/__tests__/TextInput.test.tsx
  src/components/Inputs/__tests__/TextareaInput.test.tsx
  src/components/Inputs/types.ts
  src/components/Popup/index.tsx
  src/utils/.gitkeep
  src/utils/cn.ts
Labels: feature

#94 feat: 토스트 컴포넌트 구현
  public/icons/alert-circle.svg
  src/app/entry-meeting/_components/LinkInput.tsx
  src/app/meeting/info/_components/MeetingDetail.tsx
  src/app/meeting/photo-capture/_utils/base64ToFile.ts
  src/app/meeting/photo-capture/_utils/formatCaptureTime.ts
  src/app/meeting/photo/[photoId]/formatCaptureTime.ts
  src/components/Callout/index.stories.tsx
  src/components/Callout/index.tsx
  src/components/QRPopup/index.tsx
  src/components/Toast/index.stories.tsx
  src/components/Toast/index.tsx
Labels: feature

#96 feat: 실제 참여자 수 데이터로 총 인원 수 표시 업데이트
  src/app/meeting/info/_components/MeetingDetail.tsx
Labels: feature, in progress

#97 feat : ColorPicker 컴포넌트 생성
  src/app/create-meeting/_components/MeetingTheme.tsx
  src/components/ColorPicker/index.stories.tsx
  src/components/ColorPicker/index.tsx
Labels: feature, refactor

#99 feat: 모임 정보 수정 페이지 구현
  .vscode/settings.json
  src/apis/apiUtils.ts
  src/apis/queries/meetingQueries.ts
  src/app/entry-meeting/_components/MeetingInfo.tsx
  src/app/manage-meeting/page.tsx
  src/app/meeting/info/_components/MeetingDetail.tsx
  src/app/meeting/info/page.tsx
  src/components/ColorPicker/index.stories.tsx
  src/components/ColorPicker/index.tsx
  src/components/Toast/index.tsx
  src/constant/color.ts
  src/stores/useToastStore.ts
  src/utils/errorMessages.ts
Labels: feature, in progress

#101 feat: Popup 컴포넌트에 close 버튼 속성 추가
  public/icons/CloseSvg.tsx
  public/icons/close.svg
  src/app/create-meeting/_components/Page.tsx
  src/app/entry-meeting/_components/Welcome.tsx
  src/app/manage-mission/_components/NewMission.tsx
  src/app/meeting/photo-capture/_components/CameraView.tsx
  src/app/meeting/photo-capture/_components/PhotoView.tsx
  src/app/meeting/photo/[photoId]/page.tsx
  src/components/Popup/index.stories.tsx
  src/components/Popup/index.tsx
  src/components/QRPopup/index.tsx
Labels: feature, enhancement

#113 feat: 모임 재입장 로직 추가
  .eslintrc.json
  src/apis/PasswordPopup.tsx
  src/apis/apiUtils.ts
  src/app/layout.tsx
  src/components/Popup/index.tsx
  src/stores/usePasswordPopupStore.ts
Labels: feature

#116 refactor: dpr 적용으로 사진 화질 개선
  src/app/meeting/photo-capture/_components/CameraView.tsx
  src/app/meeting/photo-capture/_components/PhotoView.tsx
  src/hooks/useCamera.ts
Labels: enhancement
