Repository dnd-side-project/dnd-11th-6-frontend, pull requests merged in 2024-08, with the labels that each got.

#16 미션, 모임 생성하는 UI 및 최소 기능 구현
  .eslintrc.json
  src/app/create-meeting/_components/MeetingAdminPin.tsx
  src/app/create-meeting/_components/MeetingInfo.tsx
  src/app/create-meeting/_components/MeetingPassword.tsx
  src/app/create-meeting/_components/MeetingShare.tsx
  src/app/create-meeting/_components/MeetingTheme.tsx
  src/app/create-meeting/_components/index.ts
  src/app/create-meeting/_hooks/useMeetingForm.ts
  src/app/create-meeting/page.tsx
  src/app/create-mission/page.tsx
  src/app/page.tsx
  src/components/Form/Input/FormInput.tsx
  src/hooks/.gitkeep
  src/hooks/useZodForm.ts
  src/lib/meetingSchema.ts
  src/stores/useMeetStore.ts
  src/stores/useMissionStore.ts
  src/stores/useStore.ts
  src/types/.gitkeep
Labels: feature, enhancement

#21 feat: 카메라 촬영 기능 구현
  .eslintrc.json
  src/app/layout.tsx
  src/app/meeting/[meetingId]/MeetingPageClient.tsx
  src/app/meeting/photo-capture/_components/CameraView.tsx
  src/app/meeting/photo-capture/_components/PhotoView.tsx
  src/app/meeting/photo-capture/page.tsx
  src/assets/CameraCaptureButton.svg
  src/assets/CameraSwitchButton.svg
  src/assets/Refresh.svg
  src/assets/close.svg
  src/hooks/useCamera.ts
  src/utils/imageUtils.ts
Labels: feature, in progress

#22 Feature/storybook minimal input button
  .eslintrc.json
  .storybook/preview.ts
  package.json
  src/app/create-meeting/_components/MeetingInfo.tsx
  src/app/create-meeting/_components/MeetingPassword.tsx
  src/app/entry-meeting/_components/NicknameInput.tsx
  src/app/entry-meeting/_components/PasswordInput.tsx
  src/components/Button/Button.tsx
  src/components/Button/index.stories.tsx
  src/components/Button/index.tsx
  src/components/Form/Input/FormInput.tsx
  src/components/Input/index.stories.tsx
  src/components/Input/index.tsx
  src/styles/globals.css
Labels: feature, enhancement, refactor

#24 feat : 모임 생성 폼 데이터 유지 기능 구현
  .eslintrc.json
  src/app/create-meeting/_components/MeetingInfo.tsx
  src/app/create-meeting/_hooks/useMeetingForm.ts
  src/app/create-meeting/page.tsx
  src/app/layout.tsx
  src/app/meeting/photo-capture/_components/PhotoView.tsx
  src/components/Input/index.stories.tsx
  src/components/Input/index.tsx
  src/lib/meetingSchema.ts
  src/stores/useMeetStore.ts
Labels: bug, refactor

#26 feat : 메인화면 스크롤 구현
  public/Image.svg
  public/image1.svg
  public/image2.svg
  public/image3.svg
  public/lock-slash.svg
  public/logo.svg
  src/app/create-meeting/_components/MeetingTheme.tsx
  src/app/page.tsx
  tailwind.config.ts
Labels: task, in progress

#30 feat: button, input, callout 컴포넌트 구현
  .storybook/preview.ts
  public/icons/back.svg
  public/icons/check.svg
  public/icons/crown.svg
  public/icons/double-down.svg
  public/icons/down.svg
  public/icons/download.svg
  public/icons/info.svg
  public/icons/lock-slash.svg
  public/icons/magic-wand.svg
  public/icons/meatballs-menu.svg
  public/icons/photo.svg
  public/icons/plus.svg
  public/icons/snap.svg
  public/icons/up.svg
  src/components/Button/index.stories.tsx
  src/components/Button/index.tsx
  src/components/Callout/index.stories.tsx
  src/components/Callout/index.tsx
  src/components/Input/index.stories.tsx
  src/components/Input/index.tsx
Labels: feature, in progress

#31 chore: 로컬 개발 서버 접근 가능
  package.json
Labels: enhancement

#36 chore: storybook auto docs 추가
  .storybook/main.ts
Labels: enhancement

#40 feat : main 화면 레이아웃 변경 및 코드 리팩토링
  public/icons/logo-white.svg
  src/app/_components/FeatureItem.tsx
  src/app/_components/TeamMember.tsx
  src/app/_components/sections/Section1.tsx
  src/app/_components/sections/Section2.tsx
  src/app/_components/sections/Section3.tsx
  src/app/_components/sections/Section4.tsx
  src/app/_components/sections/Section5.tsx
  src/app/_components/sections/index.ts
  src/app/create-meeting/_components/index.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Button/index.tsx
Labels: refactor

#39 feat: 모임 입장 페이지 구현
  package.json
  public/icons/close.svg
  public/icons/meatballs.svg
  src/app/entry-meeting/_components/LinkInput.tsx
  src/app/entry-meeting/_components/MeetingInfo.tsx
  src/app/entry-meeting/_components/NicknameInput.tsx
  src/app/entry-meeting/_components/PasswordInput.tsx
  src/app/entry-meeting/_components/Welcome.tsx
  src/app/entry-meeting/_components/index.ts
  src/app/entry-meeting/page.tsx
  src/app/layout.tsx
  src/app/providers.tsx
  src/components/Callout/index.tsx
  src/components/Input/index.tsx
  src/hooks/useDeboune.ts
  src/stores/useMeetingStore.ts
  tailwind.config.ts
Labels: feature, in progress

#47 feat: popup 컴포넌트 구현
  src/components/Button/index.tsx
  src/components/Popup/index.stories.tsx
  src/components/Popup/index.tsx
Labels: feature, in progress

#45 feat: 멤버 미션 선택하기 UI 구현
  public/icons/refresh.svg
  public/icons/twinkle.svg
  src/app/create-mission/page.tsx
  src/components/Button/index.tsx
Labels: feature, in progress

#43 feat: 멤버 카메라 촬영, 촬영한 사진 확인 UI 구현
  src/app/create-mission/page.tsx
  src/app/entry-meeting/_components/PasswordInput.tsx
  src/app/meeting/photo-capture/_components/CameraView.tsx
  src/app/meeting/photo-capture/_components/PhotoView.tsx
  src/components/Tooltip/index.stories.tsx
  src/components/Tooltip/index.tsx
  src/hooks/usePhoto.ts
  src/stores/useTooltipStore.ts
  src/utils/imageUtils.ts
Labels: feature, in progress

#49 feat: 모임 입장 api 호출 로직 구현
  next.config.mjs
  package.json
  public/icons/CrownSvg.tsx
  public/icons/crown.svg
  server.mjs
  src/apis/queries/meetingQueries.ts
  src/app/create-mission/page.tsx
  src/app/entry-meeting/_components/LinkInput.tsx
  src/app/entry-meeting/_components/MeetingInfo.tsx
  src/app/entry-meeting/_components/NicknameInput.tsx
  src/app/entry-meeting/_components/PasswordInput.tsx
  src/app/entry-meeting/_components/Welcome.tsx
  src/app/entry-meeting/_hooks/usePasswordValidation.ts
  src/app/entry-meeting/page.tsx
  src/components/ToogleSwitch/index.stories.tsx
  src/components/ToogleSwitch/index.tsx
  src/stores/useUserStore.ts
  tsconfig.json
Labels: feature, in progress

#50 feat : 모임생성 기능구현 완료
  package.json
  public/icons/alert.svg
  public/icons/camera.svg
  public/icons/createLoading.svg
  public/icons/delete.svg
  public/icons/home.svg
  public/icons/share.svg
  src/apis/meetingApi.ts
  src/apis/queries/.gitkeep
  src/app/_components/FeatureItem.tsx
  src/app/_components/sections/Section5.tsx
  src/app/create-meeting/_components/MeetingAdminPin.tsx
  src/app/create-meeting/_components/MeetingDate.tsx
  src/app/create-meeting/_components/MeetingInfo.tsx
  src/app/create-meeting/_components/MeetingLayout.tsx
  src/app/create-meeting/_components/MeetingPassword.tsx
  src/app/create-meeting/_components/MeetingShare.tsx
  src/app/create-meeting/_components/MeetingTheme.tsx
  src/app/create-meeting/_components/index.ts
  src/app/create-meeting/_hooks/useMeetingForm.ts
  src/app/create-meeting/page.tsx
  src/components/Button/index.tsx
  src/components/Input/index.tsx
  src/components/ProgressBar/index.stories.tsx
  src/components/ProgressBar/index.tsx
  src/components/Tooltip/index.stories.tsx
  src/components/Tooltip/index.tsx
  src/constant/color.ts
  src/lib/meetingSchema.ts
  src/lib/meetingTypes.ts
  src/stores/useMeetStore.ts
  src/stores/useTooltipStore.ts
  src/stories/.gitkeep
  src/utils/qrCode.ts
Labels: feature, task, refactor, in progress

#54 feat: 모임 상세 페이지 구현(모임 정보/모임 키우기)
  public/icons/close.svg
  public/icons/edit.svg
  public/icons/leader.svg
  public/icons/link.svg
  public/icons/share.svg
  src/apis/apiUtils.ts
  src/apis/queries/meetingQueries.ts
  src/apis/queries/missionQuries.ts
  src/apis/queries/participantsQueries.ts
  src/app/create-mission/page.tsx
  src/app/entry-meeting/_components/LinkInput.tsx
  src/app/entry-meeting/_components/MeetingInfo.tsx
  src/app/entry-meeting/_components/NicknameInput.tsx
  src/app/entry-meeting/_components/PasswordInput.tsx
  src/app/entry-meeting/page.tsx
  src/app/meeting/[meetingId]/info/_components/MeetingDetail.tsx
  src/app/meeting/[meetingId]/info/_components/MeetingRaising.tsx
  src/app/meeting/[meetingId]/info/page.tsx
  src/components/Button/index.tsx
  src/components/QRPopup/index.stories.tsx
  src/components/QRPopup/index.tsx
  src/hooks/useDebounce.ts
  src/stores/useMeetingStore.ts
  src/stores/useUserStore.ts
  tailwind.config.ts
Labels: feature

#65 fix: 아이콘 위치 조정
  src/components/ToogleSwitch/index.tsx
Labels: enhancement

#68 fix: password input 메세지 버그 수정
  src/app/entry-meeting/_components/NicknameInput.tsx
Labels: bug, enhancement
